numbers = [1, 2, 3, 4, 5]
# numbers.insert(0, -1)
# numbers.append(20)
# numbers.pop()
# numbers.remove(3)
# numbers.clear ()
# numbers.index(5)
# print(1 in numbers)
# print(len(numbers))
# numbers.sort()
# numbers.reverse()
numbers2 = numbers.copy()
print(numbers2)
print(numbers)